import supabase
import os
def sign_up_user(email, password, first_name, last_name):
    # 1. Create the user in Supabase Auth
    res = supabase.auth.sign_up({
        "email": email,
        "password": password,
    })
    
    if res.user:
        # 2. Link to your 'Profiles' table (since auth.users is protected)
        # We use the UUID or ID generated by Supabase
        profile_data = {
            "fname": first_name,
            "lname": last_name,
            "email": email,
            "qr_code_token": f"QR-{first_name[0]}{last_name[0]}-{os.urandom(2).hex()}"
        }
        supabase.table("Profiles").insert(profile_data).execute()
        return "Registration successful! Please check your email for confirmation."
    return "Registration failed."


def login_user(email, password):
    res = supabase.auth.sign_in_with_password({
        "email": email,
        "password": password,
    })
    
    # This is your JWT
    jwt = res.session.access_token
    refresh_token = res.session.refresh_token
    
    print(f"Login successful. Your JWT: {jwt}")
    return jwt